# Use a base image
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0
# Set working directory
WORKDIR /app

# Copy project files 
COPY . /app

# Build and publish (if necessary)
RUN dotnet publish -c Release -o out

# Function runtime's entrypoint
ENTRYPOINT ["dotnet", "out/MyFunctionApp.dll"] 
